
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;



CREATE TABLE DEPARTMENT (
    DepartmentID SERIAL PRIMARY KEY,            -- SERIAL makes the ID numbers count up automatically
    DepartmentName VARCHAR(100) NOT NULL UNIQUE,
    ManagerEmpID INT NULL                       -- Links to the Employee who manages this department
);

CREATE TABLE ALLOWANCE_TYPE (
    AllowanceTypeID SERIAL PRIMARY KEY,
    AllowanceName VARCHAR(100) NOT NULL UNIQUE,
    Description VARCHAR(255) NULL
);



CREATE TABLE EMPLOYEE (
    EmployeeID SERIAL PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    JobTitle VARCHAR(100) NOT NULL,
    DepartmentID INT REFERENCES DEPARTMENT(DepartmentID)
);


ALTER TABLE DEPARTMENT ADD FOREIGN KEY (ManagerEmpID) REFERENCES EMPLOYEE(EmployeeID);

CREATE TABLE USER_ACCOUNT (
    UserAccountID SERIAL PRIMARY KEY,
    EmployeeID INT UNIQUE REFERENCES EMPLOYEE(EmployeeID) ON DELETE CASCADE,
    PasswordHash VARCHAR(255) NOT NULL, 
    Role VARCHAR(30) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE     
);



CREATE TABLE PAYROLLRUN (
    PayrollRunID SERIAL PRIMARY KEY,
    UserAccountID INT REFERENCES USER_ACCOUNT(UserAccountID), 
    RunDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PayPeriodStart DATE NOT NULL,
    PayPeriodEnd DATE NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Draft'
);

CREATE TABLE PAYSLIP (
    PayslipID SERIAL PRIMARY KEY,
    EmployeeID INT REFERENCES EMPLOYEE(EmployeeID),
    PayrollRunID INT REFERENCES PAYROLLRUN(PayrollRunID) ON DELETE CASCADE,
    BasicSalary DECIMAL(12,2) NOT NULL,
    NetPay DECIMAL(12,2) NOT NULL DEFAULT 0.00
);


CREATE TABLE OVERTIME_ENTRY (
    OvertimeID SERIAL PRIMARY KEY,
    EmployeeID INT REFERENCES EMPLOYEE(EmployeeID),
    PayrollRunID INT REFERENCES PAYROLLRUN(PayrollRunID),
    HoursWorked DECIMAL(5,2) NOT NULL,
    RatePerHour DECIMAL(10,2) NOT NULL
);

CREATE TABLE DEDUCTION (
    DeductionID SERIAL PRIMARY KEY,
    PayslipID INT REFERENCES PAYSLIP(PayslipID) ON DELETE CASCADE,
    DeductionType VARCHAR(50) NOT NULL,
    Amount DECIMAL(10,2) NOT NULL
);

CREATE TABLE ALLOWANCE (
    AllowanceID SERIAL PRIMARY KEY,
    PayslipID INT REFERENCES PAYSLIP(PayslipID) ON DELETE CASCADE,
    AllowanceTypeID INT REFERENCES ALLOWANCE_TYPE(AllowanceTypeID),
    Amount DECIMAL(10,2) NOT NULL
);

CREATE TABLE EMPLOYEE_ALLOWANCE (
    EmployeeAllowanceID SERIAL PRIMARY KEY,
    EmployeeID INT REFERENCES EMPLOYEE(EmployeeID),
    AllowanceTypeID INT REFERENCES ALLOWANCE_TYPE(AllowanceTypeID),
    EffectiveFromDate DATE NOT NULL,
    EffectiveToDate DATE NULL
);
